name: ImSoFunky
author: Andy Brown
title: ImSoFunky
description: 'ImSoFunky is a web design company specialising in providing services for the music industry.'
markdown: kramdown
url: 'http://localhost:4000/'
baseurl: "https://dev-folder.github.io/dev-isf"
permalink: /blog/:categories/:title/
exclude: ['README.md']
future: true
gems: [jekyll-paginate, jekyll-archives, jekyll-minifier]
paginate: 3
paginate_path: "/blog/page:num/"
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-minifier
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Social Media Accounts
facebook: imsofunky
twitter: imsofunky
instagram: imsofunky
pinterest: imsofunky
linkedin: imsofunky
youtube: imsofunky
pinterest: imsofunky
email: andy@imsofunky.com
collections:
  portfolio:
    output: true

# SEO
google-analytics: UA-4725744-16
google-search-console:
bing-analytics: 84ECEB983B8B3AC51BD42C217FE69655
bing-webmaster-tools: