name: ImSoFunky
author: Andy Brown
title: ImSoFunky
description: 'ImSoFunky is a web design company specialising in providing services for the music industry.'
markdown: kramdown
url: 'https://dev-folder.github.io/dev-isf'
baseurl: "https://dev-folder.github.io/dev-isf"
permalink: /blog/:categories/:title/
exclude: ['README.md']
future: true
gems: [jekyll-paginate]
paginate: 3
paginate_path: "/blog/page:num/"
plugins:
  - jekyll-archives
  - jekyll-paginate

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Social Media Accounts
facebook: imsofunkystudio
twitter: imsofunky
instagram: imsofunky
pinterest: imsofunky
linkedin: imsofunky
email: andy@imsofunky.com
collections:
  portfolio:
    output: true

# SEO
google-analytics:
google-search-console:
bing-analytics:
bing-webmaster-tools: